FROM golang:1.26.1-alpine AS gobuilder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
RUN apk add --no-cache bash
COPY cmd/compactor/ cmd/compactor/
COPY internal/ internal/
COPY lib/ lib/
COPY scripts/build-compactor scripts/build-compactor
ARG SIREN_VERSION=devel
ENV CGO_ENABLED=0
ENV GOFLAGS=-trimpath
RUN ./scripts/build-compactor "$SIREN_VERSION"

FROM alpine:3.22
WORKDIR /app
RUN apk add --no-cache ca-certificates
COPY --from=gobuilder /app/cmd/compactor/compactor ./compactor
ENTRYPOINT ["./compactor"]
