#!/usr/bin/env bash
set -euo pipefail

cur="$(dirname "$(readlink -f "$0")")"
cd "$cur/.."

SIREN_VERSION="${1:-$(git describe --tags)}"
SIREN_VERSION="${SIREN_VERSION#v}"
go build -o cmd/adapter-mfc/adapter-mfc -ldflags="-s -w -X 'github.com/bcmk/siren/v3/lib/cmdlib.Version=${SIREN_VERSION}'" ./cmd/adapter-mfc
