#!/bin/bash

cur="$(dirname "$(readlink -f "$0")")"
cd "$cur/../docs/icons"

exp () {
    inkscape -z --export-area-page --export-png=siren-$1x$1.png --export-width=$1 --export-height=$1 siren.svg
    inkscape -z --export-area-page --export-png=siren-round-$1x$1.png --export-width=$1 --export-height=$1 siren-round.svg
}

exp 20
exp 24
exp 32
exp 48
exp 64
exp 128
exp 196
exp 300
exp 512
exp 1024
