#!/usr/bin/env bash
set -euo pipefail

manifest_list=$(doctl registry repository list-manifests bot --output json)

get_old_digests() {
    jq -r "sort_by(.updated_at) | .[].digest" <<< "$manifest_list"
}

get_tags_from_digest() {
    jq -c --arg digest "$1" '.[] | select(.digest == $digest) | .tags // []' <<< "$manifest_list"
}

print_manifest() {
    local digest="$1"
    local tags=""
    tags=$(get_tags_from_digest "$digest")
    echo "tags: $tags, digest: $digest"
}

get_old_digests | while read -r digest; do
    print_manifest "$digest"
done
