#!/usr/bin/env bash
set -euo pipefail

if [ $# -ne 1 ]; then
    echo "usage: $0 <repo>" >&2
    exit 2
fi
repo="$1"

manifest_list=$(doctl registry repository list-manifests "$repo" --output json)

get_digests() {
    jq -r "sort_by(.updated_at) | .[].digest" <<< "$manifest_list"
}

get_tags_from_digest() {
    jq -c --arg digest "$1" '.[] | select(.digest == $digest) | .tags // []' <<< "$manifest_list"
}

print_manifest() {
    local digest="$1"
    local tags=""
    tags=$(get_tags_from_digest "$digest")
    echo "tags: $tags, digest: $digest"
}

get_digests | while read -r digest; do
    print_manifest "$digest"
done
