#!/bin/bash
conf=$1
domain=$2
certificate=$3
curl -F "url=https://$domain/$(jq -r '.bot_token' $conf)" -F "certificate=@$certificate" "https://api.telegram.org/bot$(jq -r '.bot_token' $conf)/setWebhook"
echo
