#!/bin/bash
conf=$1
domain=$2
curl -F "url=https://$domain/$(jq -r '.bot_token' $conf)" -F "certificate=@$(jq -r '.certificate' $conf)" "https://api.telegram.org/bot$(jq -r '.bot_token' $conf)/setWebhook"
echo
